export const LoginTranslations = {
  en: {
    title: "Smartle",
    email: "Email",
    password: "Password",
    remember: "Remember me",
    forgot: "Forgot password?",
    signIn: "Sign in",
    or: "Or continue with",
    google: "Sign in with Google",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
  },
  fr: {
    title: "Smartle",
    email: "E-mail",
    password: "Mot de passe",
    remember: "Souviens-toi de moi",
    forgot: "Mot de passe oublié ?",
    signIn: "Se connecter",
    or: "Ou continuer avec",
    google: "Se connecter avec Google",
    noAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
  },
  nl: {
    title: "Smartle",
    email: "E-mail",
    password: "Wachtwoord",
    remember: "Onthoud mij",
    forgot: "Wachtwoord vergeten?",
    signIn: "Inloggen",
    or: "Of ga verder met",
    google: "Inloggen met Google",
    noAccount: "Heb je nog geen account?",
    signUp: "Aanmelden",
  },
};

export const ForgotPasswordtranslations = {
  en: {
    title: "Forgot your password?",
    description:
      "Enter your email address and we'll send you a link to reset your password.",
    emailLabel: "Email address",
    placeholder: "your@email.com",
    sendLink: "Send Reset Link",
    success:
      "If this email is registered, you'll receive a password reset link shortly.",
    backToLogin: "Back to login",
    remembered: "Remembered your password?",
  },
  fr: {
    title: "Mot de passe oublié ?",
    description:
      "Entrez votre adresse e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    emailLabel: "Adresse e-mail",
    placeholder: "votre@email.com",
    sendLink: "Envoyer le lien de réinitialisation",
    success:
      "Si cet e-mail est enregistré, vous recevrez bientôt un lien de réinitialisation.",
    backToLogin: "Retour à la connexion",
    remembered: "Vous vous souvenez de votre mot de passe ?",
  },
  nl: {
    title: "Wachtwoord vergeten?",
    description:
      "Voer je e-mailadres in en we sturen je een link om je wachtwoord te resetten.",
    emailLabel: "E-mailadres",
    placeholder: "jouw@email.com",
    sendLink: "Resetlink verzenden",
    success:
      "Als dit e-mailadres is geregistreerd, ontvang je binnenkort een resetlink.",
    backToLogin: "Terug naar inloggen",
    remembered: "Wachtwoord herinnerd?",
  },
};

export const SignUpTranslations = {
  en: {
    fullName: "Full Name",
    emailAddress: "Email Address",
    createSmartleAccount: "Create your Smartle account",
    simplifyWorkFlow: "Start simplifying your invoicing workflow in minutes.",
    password: "Password",
    confirmPassword: "Confirm Password",
    iAgreeToThe: "I agree to the",
    termsOfService: "Terms of Service",
    and: "and",
    privacyPolicy: "Privacy Policy",
    createAccount: "Create Account",
    orSignUpWith: "Or sign up with",
    continueWithGoogle: "Continue with Google",
    alreadyAccount: "Already have an account?",
    logIn: "Log In",
  },
  fr: {
    fullName: "Nom complet",
    emailAddress: "Adresse e-mail",
    createSmartleAccount: "Créez votre compte Smartle",
    simplifyWorkFlow: "Simplifiez votre flux de travail de facturation en quelques minutes.",
    password: "Mot de passe",
    confirmPassword: "Confirmez le mot de passe",
    iAgreeToThe: "Je suis d'accord avec les",
    termsOfService: "Conditions d'utilisation",
    and: "et",
    privacyPolicy: "Politique de confidentialité",
    createAccount: "Créer un compte",
    orSignUpWith: "Ou inscrivez-vous avec",
    continueWithGoogle: "Continuer avec Google",
    alreadyAccount: "Vous avez déjà un compte?",
    logIn: "Se connecter",
  },
  nl: {
    fullName: "Volledige naam",
    emailAddress: "E-mailadres",
    createSmartleAccount: "Maak uw Smartle-account aan",
    simplifyWorkFlow: "Begin binnen enkele minuten met het vereenvoudigen van uw facturatieproces.",
    password: "Wachtwoord",
    confirmPassword: "Bevestig wachtwoord",
    iAgreeToThe: "Ik ga akkoord met de",
    termsOfService: "Servicevoorwaarden",
    and: "en",
    privacyPolicy: "Privacybeleid",
    createAccount: "Account aanmaken",
    orSignUpWith: "Of registreer met",
    continueWithGoogle: "Doorgaan met Google",
    alreadyAccount: "Heeft u al een account?",
    logIn: "Inloggen",
  },
};

export const TwoFactorAuthTranslations = {
  en: {
    title: "Two-Factor Authentication",
    description: "Enter the 6-digit code from your authenticator app",
    codeLabel: "Verification Code",
    placeholder: "000000",
    verify: "Verify",
    resend: "Resend Code",
    backToLogin: "Back to login",
    invalidCode: "Invalid verification code",
    codeSent: "Verification code sent successfully",
    resendIn: "Resend in",
    seconds: "seconds",
  },
  fr: {
    title: "Authentification à deux facteurs",
    description: "Entrez le code à 6 chiffres de votre application d'authentification",
    codeLabel: "Code de vérification",
    placeholder: "000000",
    verify: "Vérifier",
    resend: "Renvoyer le code",
    backToLogin: "Retour à la connexion",
    invalidCode: "Code de vérification invalide",
    codeSent: "Code de vérification envoyé avec succès",
    resendIn: "Renvoyer dans",
    seconds: "secondes",
  },
  nl: {
    title: "Twee-factor authenticatie",
    description: "Voer de 6-cijferige code in van je authenticator app",
    codeLabel: "Verificatiecode",
    placeholder: "000000",
    verify: "Verifiëren",
    resend: "Code opnieuw verzenden",
    backToLogin: "Terug naar inloggen",
    invalidCode: "Ongeldige verificatiecode",
    codeSent: "Verificatiecode succesvol verzonden",
    resendIn: "Opnieuw verzenden in",
    seconds: "seconden",
  },
};